spring:
  profiles:
    active: dev

---
spring:
  datasource:
    #    oracle数据源配置操作,默认为hikari
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: scott
      password: tiger
  config:
    activate:
      on-profile: dev
server:
  port: 12122